### PR TITLE
Add chat

### LINKED ISSUE #29: Add chat
I think a chat would be cool to have if you play against real people. Haven't seen an issue about this yet.

If I have some spare time, I can try to contribute to this project :)

### PR DESCRIPTION
**Pull request by ekzyis**
Hey!

First of all, setting up this project was surprisingly easy. Much appreciated!

Looking through the code, I was able to understand how it works and could reuse parts for a basic chat component.

I haven't styled it in any way yet. I just made it work for now. See screenshots:

2023-02-02-080122_1920x1080_scrot

2023-02-02-080141_1920x1080_scrot

Closes #29

### CODE REVIEW

**Comment by ekzyis** [comment]
Mhh, I think I should use kind 4 (encrypted direct messaging) instead of kind 30 [which is for chess moves](https://github.com/nostr-protocol/nips/pull/212).

I can just use kind 4 and refer to the event id of the chess game start as specified in [NIP-04](https://github.com/nostr-protocol/nips/blob/master/04.md). No need to specify a new "subkind" like I did here for chatting during chess matches, lol

What do you think?

**Comment by theborakompanioni** [comment]
Hey @ekzyis, nice - I like it very much.

> Mhh, I think I should use kind 4 (encrypted direct messaging) instead of kind 30 [which is for chess moves](https://github.com/nostr-protocol/nips/pull/212).
> 
> I can just use kind 4 and refer to the event id of the chess game start as specified in [NIP-04](https://github.com/nostr-protocol/nips/blob/master/04.md). No need to specify a new "subkind" like I did here for chatting during chess matches, lol
> 
> What do you think?

I think, for the initial version, it can be a normal, public chat with `kind := 1`, just referencing the start event. If there are other spectators, they too should be able to comment on the game. In a future version, an option to send a message to your opponent privately can be included.

Also, I think the chat does not necessarily has to be persisted to local storage.
I don't even know if games should be persisted in the first place. For the sake of simplicity, I am leaning towards removing storage completely. But that is another story and does not need to be addressed here.

Let's try to do the simplest thing first and then iterate on it. I am eager to merge this soon!

Also, what do you think about using the [`ChatBubble` component](https://react.daisyui.com/?path=/story/data-display-chat-bubble--with-footer)?

Thank you so much for your contribution :orange_heart:

**Comment by ekzyis** [comment]
> I think, for the initial version, it can be a normal, public chat with kind := 1, just referencing the start event. If there are other spectators, they too should be able to comment on the game. In a future version, an option to send a message to your opponent privately can be included.

Oh, guess I totally forgot about the most basic nostr event, lol. Makes sense to use it, especially because of spectators!

> Also, I think the chat does not necessarily be persisted to local storage.
I don't even know if games should be persisted in the first place. For the sake of simplicity, I am leaning towards removing storage completely. But that is another story and does not need to be addressed here.

Ahh  `db.game_chat.add` is persisting it to local storage, right? Didn't notice that; I just reused the code for the other events. But makes sense now that you mentioned it.

With "does not need to be addressed here", do you mean removing local storage completely or removing local storage for the chat?

> Also, what do you think about using the [ChatBubble component](https://react.daisyui.com/?path=/story/data-display-chat-bubble--with-footer)?

Oh, looks nice! I will use it.

> Thank you so much for your contribution :orange_heart:

Haha, no worries, will hopefully not be my last contribution!

**Comment by ekzyis** [comment]
Mhh, I pushed some changes but there is a bug:
For some reason, the black player does not receive old chat messages when loading the page.
For the white player, it works however.

**Comment by theborakompanioni** [comment]
> Mhh, I pushed some changes but there is a bug: For some reason, the black player does not receive old chat messages when loading the page. For the white player, it works however.

Thanks @ekzyis, I will take a look and try to fix any remaining issues.
Will let you know :orange_heart:

**Comment by ekzyis** [comment]
Hey, any updates on this? :) We might [ pretty sure we do, lol :) ] want to use this to stream some chess 1v1s over nostr :) 

See https://stacker.news/items/344761

**Comment by theborakompanioni** [comment]
> Hey, any updates on this? :) We might [ pretty sure we do, lol :) ] want to use this to stream some chess 1v1s over nostr :)

Hey @ekzyis, thank you so much for bringing it to my attention again.
The harsh truth is that after having some difficulties with https://github.com/jesterui/jesterui/pull/32 ("refactor: switch from FEN to PGN") I pretty much forgot about it. I am really sorry for that and did not mean to disrespect your work and your time. I hope to review it in the coming days.

However, the problem with https://github.com/jesterui/jesterui/pull/32  still stands and the current approach is simple but not flexible enough to build a serious chess protocol. Maybe you also have some thoughts on that. Any insight, comment or help is highly appreciated :pray:

**Comment by ekzyis** [comment]
> I am really sorry for that and did not mean to disrespect your work and your time.

lol, no worries, I was actually just interested to play some chess on nostr soon, lol :)

No time to reply to the other stuff right now, but I might come back to this when I do. :)

**Comment by ekzyis** [comment]
But one thing, whoever works on this: Don't use NIP04 anymore, [NIP44 will be merged soon](https://github.com/nostr-protocol/nips/pull/746#issuecomment-1849862223), probably still in this year :)

**Comment by theborakompanioni** [comment]
> But one thing, whoever works on this: Don't use NIP04 anymore, [NIP44 will be merged soon](https://github.com/nostr-protocol/nips/pull/746#issuecomment-1849862223), probably still in this year :)

Thanks for the hint. What about just using plain messages?

**Comment by ekzyis** [comment]
> Thanks for the hint. What about just using plain messages?°

I am from the camp that _if_ there is nothing speaking against encryption, you should use encryption :)

I also hope that a chess app being the first using NIP44 might make a difference in the adoption of it.

**Comment by theborakompanioni** [comment]
Closing. Superseded by https://github.com/jesterui/jesterui/pull/36

@ekzyis Feedback would be highly appreciated (still considered WIP).

**Pull request closed without merging**
